### ISSUE TITLE
license to steam

### ISSUE THREAD

**Issue by adis05** [esx-overextended/es_extended#53]
how to move license rockstart to steamhex?

**Comment by mahanmoulaei** [comment]
The real question here is WHY would you want to do that?

**Comment by iSentrie** [comment]
one of a reason is that it allows players to share their rockstar account, example 2 brothers in the same household can use 1 rockstar and different steams, so they dont need to buy 2 gta 5's

**Comment by iSentrie** [comment]
> The real question here is WHY would you want to do that?

one of a reason is that it allows players to share their rockstar account, example 2 brothers in the same household can use 1 rockstar and different steams, so they dont need to buy 2 gta 5's

**Comment by mahanmoulaei** [comment]
> one of a reason is that it allows players to share their rockstar account

I see, but doing so is not a good practice security-wise. It's exactly the reason the identifier was changed by the ESX team from Steam to R* license a couple of years ago. Since Steam hex id is easier to manipulate, if you base the framework's unique identifier for the players on that, let's say even if you ban a player, they can easily create a new account to join back the server.

On top of that, currently a lot of resources use R* license as their unique identifier for players. Even if I make it easily editable inside the framework, it's going to conflict with external resources, like ox_inventory for instance _(which is going to kick the players out)_

**Comment by iSentrie** [comment]
> > one of a reason is that it allows players to share their rockstar account
> 
> I see, but doing so is not a good practice security-wise. It's exactly the reason the identifier was changed by the ESX team from Steam to R* license a couple of years ago. Since Steam hex id is easier to manipulate, if you base the framework's unique identifier for the players on that, let's say even if you ban a player, they can easily create a new account to join back the server.
> 
> On top of that, currently a lot of resources use R* license as their unique identifier for players. Even if I make it easily editable inside the framework, it's going to conflict with external resources, like ox_inventory for instance _(which is going to kick the players out)_

bans is issued to all licenses (txadmin), not just steam or rockstar license, whoever share an account is responsible for ban, everyone in a share will be banned, it won't conflict with external resources, wont conflict with ox_inventory at all, it checks for main identifier as 99% of other resources if its supported by esx, it checks for player.identifier which is the one you set. im using steam as a main identifier and had 0 issues and only found 1 resource which was manually checking for r* indentifier instead of framework method. :)

**Comment by mahanmoulaei** [comment]
@adis05 @iSentrie 
The line below needs to be executed in one of your .cfg files before you boot up the server:
`setr esx:identifier "license"`

Here are the available identifiers:
_"steam" | "license" | "license2" | "xbl" | "ip" | "discord" | "live"  | "fivem"_
